import LegalPage from "@/components/legal/LegalPage";

export default function TermsPage() {
  return <LegalPage eyebrow="Legal" title="Terms of Service" intro="The rules for using Remote Agric and participating in the farm ownership opportunities shown on the platform." sections={[
    { title: "Using Remote Agric", content: <><p>You must provide accurate registration and billing information, keep your account credentials secure, and use the platform lawfully. You are responsible for activity carried out through your account.</p><p>Remote Agric may update, suspend, or discontinue features where reasonably necessary for security, operations, or legal compliance.</p></> },
    { title: "Farm ownership opportunities", content: <><p>Each opportunity has its own price, unit availability, duration, projected return, and harvest information. Your purchase is recorded only after payment is successfully confirmed. Availability can change before confirmation.</p><p>Descriptions, updates, and projected figures are provided for information and are not a promise of a particular harvest, return, payout date, or outcome.</p></> },
    { title: "Payments, wallets, and withdrawals", content: <><p>Payments may be made using the methods offered at checkout, including card, bank, or wallet where available. You must be authorised to use the selected payment method.</p><p>Wallet balances, withdrawal requests, bank-account verification, and payment processing are subject to the applicable platform checks and third-party payment-provider processes. Do not rely on a balance or transaction as final until its status is confirmed in your account.</p></> },
    { title: "Harvest choices and support", content: <><p>Where an opportunity permits it, you may choose the available harvest-return option through your dashboard. Timing and fulfilment depend on the project status and operational confirmation.</p><p>Use support tickets and platform communications respectfully. We may remove content or restrict access where it is abusive, unlawful, misleading, or harmful to the community.</p></> },
    { title: "Disclaimers and liability", content: <><p>Agriculture involves uncertainty. To the extent allowed by law, Remote Agric is not liable for indirect or consequential losses arising from use of the platform or outcomes of a farm cycle. Nothing in these terms excludes liability that cannot legally be excluded.</p><p>Please read the <a className="font-medium text-primary underline underline-offset-2" href="/risk-disclosure">Risk Disclosure</a> before purchasing any farm ownership unit.</p></> },
    { title: "Changes and contact", content: <p>We may revise these terms by posting an updated version here. Continued use after an update takes effect means you accept the revised terms. If you have a question, contact us before using the service.</p> },
  ]} />;
}
