"use client";
import axios from "axios";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Headphones, Loader2, MessageSquareText, Plus, Search, TicketCheck, X } from "lucide-react";
import { backendUrl, relativeTime, Ticket } from "@/lib/tickets";
import StatusBadge from "./StatusBadge";

export default function SupportDashboard({ admin = false }: { admin?: boolean }) {
  const [tickets, setTickets] = useState<Ticket[]>([]), [loading, setLoading] = useState(true), [query, setQuery] = useState("");
  const [filter, setFilter] = useState(admin ? "open" : "all"), [modal, setModal] = useState(false), [detail, setDetail] = useState<Ticket | null>(null);
  const [subject, setSubject] = useState(""), [message, setMessage] = useState(""), [category, setCategory] = useState("other"), [priority, setPriority] = useState("medium"), [submitting, setSubmitting] = useState(false);
  const base = admin ? "/api/admin/tickets" : "/api/tickets";
  const route = admin ? "/admin/dashboard/support" : "/dashboard/support";
  const load = useCallback(async () => { try { const suffix = admin ? `?status=${filter}` : ""; const { data } = await axios.get(`${backendUrl}${base}${suffix}`, { withCredentials: true }); setTickets(data.data.tickets); } finally { setLoading(false); } }, [admin, base, filter]);
  useEffect(() => { load(); }, [load]);
  const shown = useMemo(() => tickets.filter((t) => `${t.ticketNumber} ${t.subject} ${t.user?.firstName ?? ""} ${t.user?.lastName ?? ""}`.toLowerCase().includes(query.toLowerCase())), [tickets, query]);
  async function create(e: FormEvent) { e.preventDefault(); setSubmitting(true); try { await axios.post(`${backendUrl}/api/tickets`, { subject, message, category, priority }, { withCredentials: true }); setModal(false); setSubject(""); setMessage(""); await load(); } finally { setSubmitting(false); } }
  async function openDetail(ticket: Ticket) { const { data } = await axios.get(`${backendUrl}/api/admin/tickets/${ticket._id}`, { withCredentials: true }); setDetail(data.data.ticket); }
  const count = (status: string) => tickets.filter((t) => t.status === status).length;
  return <section className="min-h-full bg-[#f6f8f6] px-4 py-7 md:px-8 lg:px-10">
    <div className="mx-auto max-w-7xl">
      <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-2 text-[10px] font-extrabold uppercase tracking-[.22em] text-primary">Customer care</p><h1 className="text-2xl font-extrabold text-gray-900 md:text-3xl">{admin ? "Support centre" : "Support tickets"}</h1><p className="mt-2 text-sm text-gray-500">{admin ? "Review requests, respond to customers and manage resolutions." : "Start a conversation with our team and track every request in one place."}</p></div>{!admin && <button onClick={() => setModal(true)} className="flex items-center justify-center gap-2 rounded-xl bg-primary px-5 py-3 text-sm font-bold text-white shadow-lg shadow-green-900/10 transition hover:-translate-y-0.5 hover:bg-primary-dark"><Plus size={18}/>New ticket</button>}</div>
      <div className="mt-7 grid gap-4 sm:grid-cols-3">{[
        { label: "Total tickets", value: tickets.length, Icon: MessageSquareText, style: "text-primary bg-green-50" },
        { label: "Open", value: count("open"), Icon: Headphones, style: "text-amber-700 bg-amber-50" },
        { label: "Resolved", value: count("resolved") + count("closed"), Icon: TicketCheck, style: "text-green-700 bg-green-50" },
      ].map(({ label, value, Icon, style }) => <div key={label} className="flex items-center gap-4 rounded-2xl bg-white p-5 shadow-sm"><span className={`rounded-xl p-3 ${style}`}><Icon size={22}/></span><div><p className="text-[10px] font-extrabold uppercase tracking-widest text-gray-500">{label}</p><p className="mt-1 text-2xl font-extrabold">{value}</p></div></div>)}</div>
      <div className="mt-7 overflow-hidden rounded-2xl bg-white shadow-sm"><div className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold">{admin ? "Customer requests" : "Your requests"}</h2><p className="mt-1 text-xs text-gray-500">Select a ticket to view the conversation.</p></div><div className="flex gap-2"><div className="relative"><Search className="absolute left-3 top-2.5 text-gray-400" size={17}/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search tickets" className="w-full rounded-xl bg-gray-50 py-2.5 pl-9 pr-3 text-sm outline-none ring-primary/20 focus:ring-2"/></div>{admin && <select value={filter} onChange={(e) => setFilter(e.target.value)} className="rounded-xl bg-gray-50 px-3 text-sm outline-none"><option value="open">Open</option><option value="resolved">Resolved</option><option value="closed">Closed</option><option value="all">All</option></select>}</div></div>
        {admin && <div className="hidden grid-cols-[1fr_130px_110px_120px] items-center gap-3 border-t border-green-900/5 bg-gray-50 px-5 py-3 text-[11px] font-semibold uppercase tracking-wider text-gray-500 md:grid"><span>Ticket</span><span>Status</span><span>Last activity</span><span>Actions</span></div>}
        {loading ? <div className="flex justify-center p-16"><Loader2 className="animate-spin text-primary"/></div> : shown.length === 0 ? <div className="p-16 text-center"><MessageSquareText className="mx-auto mb-3 text-gray-300" size={36}/><p className="font-bold">No tickets found</p><p className="mt-1 text-sm text-gray-500">{admin ? "There are no tickets in this view." : "Create your first request when you need a hand."}</p></div> : <div className="divide-y divide-green-900/5">{shown.map((ticket) => <div key={ticket._id} className="grid items-center gap-3 px-5 py-4 transition hover:bg-green-50/50 md:grid-cols-[1fr_130px_110px_120px]">
          <button onClick={() => admin ? openDetail(ticket) : undefined} className="min-w-0 text-left"><div className="flex items-center gap-2"><p className="truncate text-sm font-bold text-gray-900">{ticket.subject}</p><span className={`rounded-md px-2 py-0.5 text-[9px] font-extrabold uppercase ${ticket.priority === "high" ? "bg-red-50 text-red-600" : ticket.priority === "medium" ? "bg-amber-50 text-amber-700" : "bg-gray-100 text-gray-600"}`}>{ticket.priority}</span></div><p className="mt-1 text-[10px] font-bold uppercase tracking-wider text-gray-400">#{ticket.ticketNumber}{ticket.user ? ` · ${ticket.user.firstName} ${ticket.user.lastName}` : ` · ${ticket.category.replace("-", " ")}`}</p></button>
          <StatusBadge status={ticket.status}/><span className="text-xs font-medium text-gray-500">{relativeTime(ticket.lastMessageAt)}</span><Link href={`${route}/${ticket._id}`} className="rounded-xl bg-green-50 px-3 py-2 text-center text-xs font-bold text-primary transition hover:bg-primary hover:text-white">Open chat</Link>
        </div>)}</div>}
      </div>
    </div>
    {modal && <div className="fixed inset-0 z-[70] flex items-center justify-center bg-gray-950/40 p-4 backdrop-blur-sm"><form onSubmit={create} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><h2 className="text-xl font-extrabold">Create a support ticket</h2><p className="mt-1 text-sm text-gray-500">Tell us what happened and we’ll get back to you.</p></div><button type="button" onClick={() => setModal(false)} className="rounded-lg p-2 hover:bg-gray-100"><X size={19}/></button></div><div className="mt-6 space-y-4"><label className="block text-xs font-bold text-gray-600">Subject<input required maxLength={140} value={subject} onChange={(e) => setSubject(e.target.value)} className="mt-1.5 w-full rounded-xl bg-gray-50 px-4 py-3 text-sm outline-none ring-primary/20 focus:ring-2" placeholder="A short summary"/></label><div className="grid grid-cols-2 gap-3"><label className="text-xs font-bold text-gray-600">Category<select value={category} onChange={(e) => setCategory(e.target.value)} className="mt-1.5 w-full rounded-xl bg-gray-50 px-3 py-3 text-sm"><option value="investment">Investment</option><option value="payment">Payment</option><option value="account">Account</option><option value="farm-update">Farm update</option><option value="other">Other</option></select></label><label className="text-xs font-bold text-gray-600">Priority<select value={priority} onChange={(e) => setPriority(e.target.value)} className="mt-1.5 w-full rounded-xl bg-gray-50 px-3 py-3 text-sm"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label></div><label className="block text-xs font-bold text-gray-600">Message<textarea required maxLength={4000} rows={5} value={message} onChange={(e) => setMessage(e.target.value)} className="mt-1.5 w-full resize-none rounded-xl bg-gray-50 px-4 py-3 text-sm outline-none ring-primary/20 focus:ring-2" placeholder="Include any details that will help us investigate."/></label><button disabled={submitting} className="flex w-full items-center justify-center gap-2 rounded-xl bg-primary py-3 text-sm font-bold text-white hover:bg-primary-dark disabled:opacity-50">{submitting && <Loader2 size={17} className="animate-spin"/>}Create ticket</button></div></form></div>}
    {detail && <div className="fixed inset-0 z-[70] flex items-center justify-center bg-gray-950/40 p-4 backdrop-blur-sm"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-[10px] font-extrabold uppercase tracking-widest text-primary">#{detail.ticketNumber}</p><h2 className="mt-1 text-xl font-extrabold">{detail.subject}</h2></div><button onClick={() => setDetail(null)} className="rounded-lg p-2 hover:bg-gray-100"><X size={19}/></button></div><div className="mt-6 grid grid-cols-2 gap-4 rounded-xl bg-gray-50 p-4 text-sm"><div><p className="text-[10px] font-bold uppercase text-gray-400">Customer</p><p className="mt-1 font-bold">{detail.user?.firstName} {detail.user?.lastName}</p><p className="text-xs text-gray-500">{detail.user?.email}</p></div><div><p className="text-[10px] font-bold uppercase text-gray-400">Status</p><div className="mt-1"><StatusBadge status={detail.status}/></div></div><div><p className="text-[10px] font-bold uppercase text-gray-400">Category</p><p className="mt-1 font-bold capitalize">{detail.category.replace("-", " ")}</p></div><div><p className="text-[10px] font-bold uppercase text-gray-400">Created</p><p className="mt-1 font-bold">{new Date(detail.createdAt).toLocaleDateString()}</p></div></div><Link href={`${route}/${detail._id}`} className="mt-5 block rounded-xl bg-primary py-3 text-center text-sm font-bold text-white hover:bg-primary-dark">Open ticket conversation</Link></div></div>}
  </section>;
}
