import Link from "next/link";
import { ChevronDown, CircleHelp, Mail, MessageCircleMore } from "lucide-react";

const groups = [
  { title: "Getting started", items: [["What is Remote Agric?", "Remote Agric lets you explore available farm ownership opportunities, pay for units, and follow your farm activity from your account dashboard."], ["How do I create an account?", "Select Sign Up, provide your details, verify the one-time code sent during registration, then sign in. You can also use the supported Google sign-in option."], ["Can I browse opportunities before signing in?", "Yes. Opportunity listings and their details are publicly viewable. You will need an account to complete a purchase and use dashboard features."]] },
  { title: "Farm ownership and harvests", items: [["How do I buy farm ownership units?", "Open an opportunity, choose the number of units within its available limits, and continue to checkout. Your ownership is created after payment is successfully verified."], ["Are returns guaranteed?", "No. Agriculture has real operational and market risks. Project figures are projections, not promises. Review each opportunity and our Risk Disclosure before paying."], ["How will I know what is happening with my farm?", "Your dashboard shows your investments and transaction history. The platform can also provide project-stage notifications as an opportunity moves through its cycle."], ["Can I receive physical produce?", "Where an opportunity provides a harvest choice, you can select the available option from your investment dashboard when the project reaches that stage. Availability and timing depend on the project."]] },
  { title: "Payments and wallet", items: [["Which payment methods are supported?", "Checkout currently presents card, bank, and wallet payment options where available. Payment processing and confirmation are handled through the checkout flow."], ["When is a payment complete?", "A payment is complete only after the provider and Remote Agric verify it. If you are redirected for payment, return through the verification flow and check your dashboard before assuming it succeeded."], ["How do wallet withdrawals work?", "Add and verify a bank account from your dashboard, then request a withdrawal of an available wallet balance. Withdrawal requests and transfer completion can take time and are subject to platform and provider checks."]] },
  { title: "Account, support, and learning", items: [["What if I forget my password?", "Use the Forgot Password link on the sign-in page to request a reset and follow the instructions sent to your registered email."], ["How do I get help with a transaction or account?", "Signed-in users can create a support ticket from the dashboard and continue the conversation there. You can also contact the team through the Contact page."], ["What is Agri-Learn?", "Agri-Learn is Remote Agric’s public learning hub for published agriculture articles and podcast episodes. It is educational content, not personalised financial advice."], ["Can I refer someone?", "Eligible signed-in users can find their referral code and sharing link on the Referrals page in the dashboard. Referral status and rewards are shown there."]] },
];

export default function FAQsPage() {
  return <main className="min-h-screen bg-[#f6f8f6] py-12 sm:py-16"><div className="mx-auto max-w-5xl px-5 sm:px-8"><header className="text-center"><div className="mx-auto grid size-12 place-items-center rounded-2xl bg-primary/10 text-primary"><CircleHelp size={25} /></div><p className="mt-5 text-xs font-semibold uppercase tracking-[0.18em] text-primary">Help center</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-slate-900 sm:text-4xl">Frequently asked questions</h1><p className="mx-auto mt-4 max-w-2xl leading-7 text-slate-600">Answers based on how Remote Agric’s account, checkout, wallet, support, referral, and learning features work today.</p></header><div className="mt-12 grid gap-6 md:grid-cols-2">{groups.map((group) => <section key={group.title} className="rounded-3xl bg-white p-6 shadow-sm sm:p-7"><h2 className="text-lg font-semibold text-slate-900">{group.title}</h2><div className="mt-4 divide-y divide-slate-100">{group.items.map(([question, answer]) => <details key={question} className="group py-1.5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 py-3 text-sm font-medium text-slate-800">{question}<ChevronDown className="shrink-0 text-primary transition-transform group-open:rotate-180" size={18} /></summary><p className="pb-3 text-sm leading-6 text-slate-600">{answer}</p></details>)}</div></section>)}</div><section className="mt-8 flex flex-col items-center justify-between gap-5 rounded-3xl bg-primary px-6 py-7 text-center text-white sm:flex-row sm:px-8 sm:text-left"><div><h2 className="text-lg font-semibold">Still need help?</h2><p className="mt-1 text-sm text-white/80">Send us a message, or raise a ticket from your dashboard if you are signed in.</p></div><Link href="/contact" className="inline-flex shrink-0 items-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-semibold text-primary"><Mail size={16} /> Contact us</Link></section><p className="mt-5 text-center text-xs text-slate-500"><MessageCircleMore className="mr-1 inline" size={14} /> For farm-outcome and payment risks, please also read the <Link className="text-primary underline" href="/risk-disclosure">Risk Disclosure</Link>.</p></div></main>;
}
