"use client";
import { FormEvent, useEffect, useState } from "react";
import { toast } from "react-toastify";
type Produce = { _id: string; produceName: string; title: string };
const base = process.env.NEXT_PUBLIC_BACKEND_URL;
export default function AdminNotificationsPage() {
  const [produce, setProduce] = useState<Produce[]>([]), [produceId, setProduceId] = useState(""), [title, setTitle] = useState(""), [message, setMessage] = useState(""), [saving, setSaving] = useState(false);
  useEffect(() => { fetch(`${base}/api/admin/produce`, { credentials: "include" }).then((response) => response.json()).then((data) => { const active = (data.produce ?? []).filter((item: any) => item.status === "active"); setProduce(active); setProduceId(active[0]?._id ?? ""); }); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { const response = await fetch(`${base}/api/admin/notifications`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ produceId, title, message }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message); toast.success("Notification sent to active remote farmers"); setTitle(""); setMessage(""); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to send notification"); } finally { setSaving(false); } };
  return <div className="p-6"><div className="mx-auto max-w-2xl"><h1 className="text-3xl font-bold text-slate-900">Create notification</h1><p className="mt-1 text-slate-500">Send an in-app update to active remote farmers for a produce.</p><form onSubmit={submit} className="mt-8 space-y-5 rounded-2xl border bg-white p-6 shadow-sm"><label className="block text-sm font-bold">Active produce<select required value={produceId} onChange={(e) => setProduceId(e.target.value)} className="mt-2 w-full rounded-xl border p-3 font-normal"><option value="">Select produce</option>{produce.map((item) => <option key={item._id} value={item._id}>{item.produceName} — {item.title}</option>)}</select></label><label className="block text-sm font-bold">Title<input required maxLength={120} value={title} onChange={(e) => setTitle(e.target.value)} className="mt-2 w-full rounded-xl border p-3 font-normal" /></label><label className="block text-sm font-bold">Message<textarea required maxLength={1000} value={message} onChange={(e) => setMessage(e.target.value)} className="mt-2 min-h-36 w-full rounded-xl border p-3 font-normal" /></label><button disabled={saving || !produceId} className="w-full rounded-xl bg-primary py-3 font-bold text-white disabled:opacity-50">{saving ? "Sending…" : "Send notification"}</button></form></div></div>;
}
